### ISSUE TITLE
Adding support for x64 bit

### ISSUE THREAD

**Issue by MilkGames** [c4fe/glua-steal#6]
I'm pretty sure this doesn't support 64 bit, atleast I haven't gotten it to work on my Linux machine.

**Comment by lewez** [comment]
Yeah this will only work on 32-bit Garry's Mod at the moment. I'm not currently planning on extending this to support 64-bit any time soon.

**Comment by SneakySqwuid** [comment]
> Yeah this will only work on 32-bit Garry's Mod at the moment. I'm not currently planning on extending this to support 64-bit any time soon.

boo!
