### ISSUE TITLE
Failed to initialize on injection

### ISSUE THREAD

**Issue by Yogpod** [c4fe/glua-steal#7]
Video of exactly what I did:
https://propkill.me/pls/CmHXTa.mp4
the error is 
`[07-03-20 - 15:10:27.901] [info] Initializing gluasteal v1.4
[07-03-20 - 15:10:27.903] [critical] Failed to initialize: failed to grab handle for library garrysmod/bin/lua_shared
`
It's probably because of the branch i'm on but it's the 32bit build

**Comment by c4fe** [comment]
Not too sure what the issue is here. v1.4 is still working fine for me on the default 32-bit branch. The things I'd try would be:
- Verify the integrity of Garry's Mod through Steam
- Restore default injection settings in your injector
- Ensure you're on the latest version on Garry's Mod

**Comment by old-pikachu** [comment]
using standard garry's mod, NOT BETA (for example, chromium is not supported, others are possible, too)
