### ISSUE TITLE
Can't Generate the SLN project file

### ISSUE THREAD

**Issue by t3r00t** [c4fe/glua-steal#9]
Hello ,
I tried download the src and when i launch the command : 
'msbuild gluasteal.sln /p:Configuration=Release'

I get this result : 
MSBUILD : error MSB1009: Le fichier projet n'existe pas.
Commutateur : gluasteal.sln

Any idea ?

**Comment by c4fe** [comment]
Have you generated the gluasteal.sln file with cmake?

**Comment by SneakySqwuid** [comment]
glua steal bad! real men use friendly stealer!!

**Comment by t3r00t** [comment]
When i run CMake .. i dont get any sln files nor cpp or headers in the build file 
Here is the output of cmake .. 

Here is a screen of VS 2019 CMD
http://prntscr.com/s5tr40

thanks for the reply mate 👍

**Comment by c4fe** [comment]
Can you post a screenshot of all the files inside your build directory?

**Comment by t3r00t** [comment]
http://prntscr.com/s6997o
http://prntscr.com/s699e7

They all have thoses two files inside

**Comment by c4fe** [comment]
Try giving that a go. E.g. cmake -G "Visual Studio 15 2017" ..

**Comment by t3r00t** [comment]
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "C:/Users/BeastOo/Desktop/buildingdll/glua-steal/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Can you send me the latest version with sln ?

**Comment by c4fe** [comment]
That's strange. I've just tested it now and cmake it still creating a project file for me. Do you have Visual Studio installed along with all of the build tools and the 'Desktop development with C++' package? You can check in the Visual Studio Installer.

**Comment by t3r00t** [comment]
Yes i have everything installed : http://prntscr.com/s6t92v
I open this : http://prntscr.com/s6ta25

Can you add me on discord ? t3r00t#8168

**Comment by t3r00t** [comment]
I installed Visual Studio on a new Windows 10 Install and it worked without any issue , Sorry for that mate.
Something was wrong with my main computer
Thanks alot ;)
